"""Recommendation routes (read-only).

GET /recommendations returns personalized savings tips for the authenticated user.
Recommendations are typically generated by the backend (e.g. from spending analysis);
the client does not create, update, or delete them.
"""

from fastapi import APIRouter, Depends

from app.auth import get_current_user_id
from app.database import query
from app.schemas import RecommendationResponse

router = APIRouter(prefix="/recommendations", tags=["recommendations"])


@router.get("", response_model=list[RecommendationResponse])
def list_recommendations(
    user_id: str = Depends(get_current_user_id),
):
    """List recommendations for the current user, newest first."""
    return query(
        "SELECT * FROM recommendations WHERE user_id = %s ORDER BY created_at DESC",
        (user_id,),
    )
