/// Data model representing a spending limit for one category over a time period.
///
/// Maps to the `Budget` table in PostgreSQL:
/// - [id]          – unique identifier.
/// - [userId]      – foreign key linking to the owning User.
/// - [category]    – the spending category this limit applies to (e.g. “Food”).
/// - [limitAmount] – maximum dollar amount the user should spend in [period].
/// - [period]      – time window: `'weekly'`, `'monthly'`, or `'yearly'`.
/// - [createdAt]   – when this budget was generated or created.
///
/// Budgets can be auto-generated by the ML pipeline or manually set by the user.
class Budget {
  final String id;
  final String userId;
  final String category;
  final double limitAmount;
  final String period; // 'weekly', 'monthly', 'yearly'
  final DateTime createdAt;

  const Budget({
    required this.id,
    required this.userId,
    required this.category,
    required this.limitAmount,
    required this.period,
    required this.createdAt,
  });

  /// Deserialise a [Budget] from a JSON map returned by the API.
  factory Budget.fromJson(Map<String, dynamic> json) {
    return Budget(
      id: json['id'] as String,
      userId: json['user_id'] as String,
      category: json['category'] as String,
      limitAmount: (json['limit_amount'] as num).toDouble(),
      period: json['period'] as String,
      createdAt: DateTime.parse(json['created_at'] as String),
    );
  }

  /// Serialise this [Budget] to a JSON map for API requests.
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'user_id': userId,
      'category': category,
      'limit_amount': limitAmount,
      'period': period,
      'created_at': createdAt.toIso8601String(),
    };
  }

  /// Return a copy with selected fields replaced.
  Budget copyWith({
    String? id,
    String? userId,
    String? category,
    double? limitAmount,
    String? period,
    DateTime? createdAt,
  }) {
    return Budget(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      category: category ?? this.category,
      limitAmount: limitAmount ?? this.limitAmount,
      period: period ?? this.period,
      createdAt: createdAt ?? this.createdAt,
    );
  }
}
