/// Represents an ML-generated spending recommendation.
/// 
/// Recommendations are generated by analyzing user spending patterns
/// and suggest ways to optimize spending with estimated [potentialSavings].
class Recommendation {
  /// Unique identifier for the recommendation.
  final String id;
  
  /// Category this recommendation applies to (e.g., 'Food', 'Transport').
  final String category;
  
  /// Short title summarizing the recommendation.
  final String title;
  
  /// Detailed explanation of the recommendation.
  final String description;
  
  /// Estimated amount the user could save by following this recommendation.
  final double potentialSavings;

  /// Creates a new [Recommendation] instance.
  const Recommendation({
    required this.id,
    required this.category,
    required this.title,
    required this.description,
    required this.potentialSavings,
  });

  /// Creates a [Recommendation] instance from a JSON map.
  /// 
  /// Expects keys: 'id', 'category', 'title', 'description', and 'potential_savings'.
  factory Recommendation.fromJson(Map<String, dynamic> json) {
    return Recommendation(
      id: json['id'] as String,
      category: json['category'] as String,
      title: json['title'] as String,
      description: json['description'] as String,
      potentialSavings: (json['potential_savings'] as num).toDouble(),
    );
  }

  /// Converts this [Recommendation] instance to a JSON map.
  /// 
  /// Returns a map with keys: 'id', 'category', 'title', 'description', and 'potential_savings'.
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'category': category,
      'title': title,
      'description': description,
      'potential_savings': potentialSavings,
    };
  }

  /// Creates a copy of this [Recommendation] with the given fields replaced.
  /// 
  /// Any field left as null will retain its current value.
  Recommendation copyWith({
    String? id,
    String? category,
    String? title,
    String? description,
    double? potentialSavings,
  }) {
    return Recommendation(
      id: id ?? this.id,
      category: category ?? this.category,
      title: title ?? this.title,
      description: description ?? this.description,
      potentialSavings: potentialSavings ?? this.potentialSavings,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Recommendation &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          category == other.category &&
          title == other.title &&
          description == other.description &&
          potentialSavings == other.potentialSavings;

  @override
  int get hashCode =>
      Object.hash(id, category, title, description, potentialSavings);

  @override
  String toString() =>
      'Recommendation(id: $id, title: $title, savings: $potentialSavings)';
}
