/// Data model representing an authenticated SmartSpend user.
///
/// Maps to the `User` table in the PostgreSQL database:
/// - [id]        – unique identifier generated by the backend.
/// - [email]     – the user's login email.
/// - [name]      – display name.
/// - [createdAt] – timestamp when the account was created.
///
/// Provides:
/// - [fromJson] / [toJson] for REST API serialisation.
/// - [copyWith] for creating modified copies (immutable pattern).
class User {
  final String id;
  final String email;
  final String name;
  final DateTime createdAt;

  const User({
    required this.id,
    required this.email,
    required this.name,
    required this.createdAt,
  });

  /// Deserialise a [User] from a JSON map returned by the API.
  /// Keys use snake_case to match the Python backend convention.
  factory User.fromJson(Map<String, dynamic> json) {
    return User(
      id: json['id'] as String,
      email: json['email'] as String,
      name: json['name'] as String,
      createdAt: DateTime.parse(json['created_at'] as String),
    );
  }

  /// Serialise this [User] to a JSON map suitable for API requests.
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'email': email,
      'name': name,
      'created_at': createdAt.toIso8601String(),
    };
  }

  /// Return a new [User] with selected fields replaced.
  /// Unspecified fields retain their current values.
  User copyWith({
    String? id,
    String? email,
    String? name,
    DateTime? createdAt,
  }) {
    return User(
      id: id ?? this.id,
      email: email ?? this.email,
      name: name ?? this.name,
      createdAt: createdAt ?? this.createdAt,
    );
  }
}
