"""Training corpus for the transaction-categorization model.

Pure data module - no behaviour. Kept separate from the engine so the engine
file stays focused on logic and so the corpus can grow without forcing a
re-read of the algorithm. Add ``(description, label)`` pairs to teach the
model new merchants/keywords; the model is re-trained in-memory on first use.

The labels MUST be drawn from :data:`CATEGORIES` - a startup self-check in
:mod:`app.ml.categorizer` enforces this so a typo doesn't silently introduce
an out-of-vocabulary class.
"""

from __future__ import annotations

CATEGORIES: list[str] = [
    "Food",
    "Entertainment",
    "Bills",
    "Shopping",
    "Transportation",
    "Healthcare",
    "Education",
    "Other",
]


TRAINING_DATA: list[tuple[str, str]] = [
    # Food
    ("Grocery Store", "Food"),
    ("grocery shopping", "Food"),
    ("Whole Foods Market", "Food"),
    ("Walmart Grocery", "Food"),
    ("Restaurant dinner", "Food"),
    ("restaurant lunch", "Food"),
    ("fast food drive through", "Food"),
    ("McDonald's", "Food"),
    ("Chipotle", "Food"),
    ("Starbucks coffee", "Food"),
    ("Coffee shop", "Food"),
    ("Dunkin Donuts", "Food"),
    ("Pizza delivery", "Food"),
    ("DoorDash order", "Food"),
    ("Uber Eats", "Food"),
    ("Grubhub delivery", "Food"),
    ("bakery pastries", "Food"),
    ("deli sandwich", "Food"),
    ("food truck lunch", "Food"),
    ("sushi bar", "Food"),
    ("Trader Joe's", "Food"),
    ("Costco groceries", "Food"),
    ("Aldi supermarket", "Food"),
    ("meal prep ingredients", "Food"),
    # Entertainment
    ("Netflix", "Entertainment"),
    ("Netflix subscription", "Entertainment"),
    ("Spotify", "Entertainment"),
    ("Spotify premium", "Entertainment"),
    ("Hulu subscription", "Entertainment"),
    ("Disney Plus", "Entertainment"),
    ("HBO Max", "Entertainment"),
    ("Apple TV+", "Entertainment"),
    ("Movie tickets", "Entertainment"),
    ("movie theater", "Entertainment"),
    ("Concert tickets", "Entertainment"),
    ("concert festival", "Entertainment"),
    ("video games", "Entertainment"),
    ("Steam purchase", "Entertainment"),
    ("PlayStation Store", "Entertainment"),
    ("Xbox Game Pass", "Entertainment"),
    ("YouTube Premium", "Entertainment"),
    ("bowling night", "Entertainment"),
    ("amusement park", "Entertainment"),
    ("museum tickets", "Entertainment"),
    ("theater show", "Entertainment"),
    ("comedy club", "Entertainment"),
    # Bills
    ("Electric Bill", "Bills"),
    ("electricity payment", "Bills"),
    ("Internet Bill", "Bills"),
    ("internet service", "Bills"),
    ("Water Bill", "Bills"),
    ("water utility", "Bills"),
    ("Gas Bill", "Bills"),
    ("natural gas utility", "Bills"),
    ("Phone Bill", "Bills"),
    ("cell phone payment", "Bills"),
    ("Car Insurance", "Bills"),
    ("auto insurance premium", "Bills"),
    ("Home Insurance", "Bills"),
    ("renters insurance", "Bills"),
    ("Rent payment", "Bills"),
    ("mortgage payment", "Bills"),
    ("cable TV", "Bills"),
    ("trash collection", "Bills"),
    ("sewer bill", "Bills"),
    ("HOA dues", "Bills"),
    # Shopping
    ("Amazon Order", "Shopping"),
    ("Amazon purchase", "Shopping"),
    ("Target", "Shopping"),
    ("Target shopping", "Shopping"),
    ("Walmart", "Shopping"),
    ("Best Buy", "Shopping"),
    ("electronics store", "Shopping"),
    ("clothing store", "Shopping"),
    ("New shoes", "Shopping"),
    ("new clothes", "Shopping"),
    ("furniture purchase", "Shopping"),
    ("IKEA", "Shopping"),
    ("home decor", "Shopping"),
    ("Holiday gifts", "Shopping"),
    ("birthday gift", "Shopping"),
    ("department store", "Shopping"),
    ("online shopping", "Shopping"),
    ("Etsy purchase", "Shopping"),
    ("eBay order", "Shopping"),
    ("thrift store", "Shopping"),
    # Transportation
    ("Gas Station", "Transportation"),
    ("gas fill up", "Transportation"),
    ("Uber ride", "Transportation"),
    ("Lyft ride", "Transportation"),
    ("taxi cab", "Transportation"),
    ("bus pass", "Transportation"),
    ("subway ticket", "Transportation"),
    ("train ticket", "Transportation"),
    ("parking fee", "Transportation"),
    ("parking garage", "Transportation"),
    ("toll road", "Transportation"),
    ("car maintenance", "Transportation"),
    ("oil change", "Transportation"),
    ("tire replacement", "Transportation"),
    ("car wash", "Transportation"),
    ("flight ticket", "Transportation"),
    ("airline booking", "Transportation"),
    # Healthcare
    ("Pharmacy", "Healthcare"),
    ("pharmacy prescription", "Healthcare"),
    ("Co-pay", "Healthcare"),
    ("doctor copay", "Healthcare"),
    ("doctor visit", "Healthcare"),
    ("dentist appointment", "Healthcare"),
    ("dental cleaning", "Healthcare"),
    ("eye exam", "Healthcare"),
    ("optometrist", "Healthcare"),
    ("hospital bill", "Healthcare"),
    ("urgent care", "Healthcare"),
    ("physical therapy", "Healthcare"),
    ("mental health counseling", "Healthcare"),
    ("health insurance", "Healthcare"),
    ("vitamins supplements", "Healthcare"),
    ("medical lab test", "Healthcare"),
    # Education
    ("Online Course", "Education"),
    ("online class", "Education"),
    ("Udemy course", "Education"),
    ("Coursera subscription", "Education"),
    ("textbook purchase", "Education"),
    ("school supplies", "Education"),
    ("tuition payment", "Education"),
    ("student loan", "Education"),
    ("workshop fee", "Education"),
    ("certification exam", "Education"),
    ("library fine", "Education"),
    ("tutoring session", "Education"),
    ("college bookstore", "Education"),
    ("Skillshare membership", "Education"),
    # Other
    ("Salary Deposit", "Other"),
    ("salary payment", "Other"),
    ("paycheck direct deposit", "Other"),
    ("freelance payment", "Other"),
    ("side hustle income", "Other"),
    ("tax refund", "Other"),
    ("ATM withdrawal", "Other"),
    ("cash withdrawal", "Other"),
    ("bank fee", "Other"),
    ("wire transfer", "Other"),
    ("venmo transfer", "Other"),
    ("zelle payment", "Other"),
    ("interest earned", "Other"),
    ("dividend payment", "Other"),
    ("reimbursement", "Other"),
    ("miscellaneous", "Other"),
]
